INSERT INTO customers (name, email, address, encryptedPassword) VALUES
    ('John Doe', 'john@example.com', '123 Main St, Anytown', 'hashedPassword1'),
    ('Jane Smith', 'jane@example.com', '456 Elm St, Othertown', 'hashedPassword2'),
    ('Alice Johnson', 'alice@example.com', '789 Oak St, Anycity', 'hashedPassword3'),
    ('Bob Brown', 'bob@example.com', '101 Pine St, Othercity', 'hashedPassword4'),
    ('Emma White', 'emma@example.com', '555 Cedar St, Anothercity', 'hashedPassword5'),
    ('William Davis', 'william@example.com', '321 Maple St, Yetanothercity', 'hashedPassword6'),
    ('Olivia Miller', 'olivia@example.com', '909 Walnut St, Newtown', 'hashedPassword7'),
    ('Liam Wilson', 'liam@example.com', '222 Birch St, Smalltown', 'hashedPassword8'),
    ('Sophia Garcia', 'sophia@example.com', '777 Spruce St, Hometown', 'hashedPassword9'),
    ('Mason Martinez', 'mason@example.com', '444 Elm St, Village', 'hashedPassword10');

INSERT INTO shipments (trackingNumber, origin, destination, status, customerId, detailed_description) VALUES
    ('ABC123', 'New York', 'Los Angeles', 'In Transit', 1, 'High-value electronics package, fragile contents'),
    ('JKL012', 'Berlin', 'Rome', 'Pending', 2, 'Fashion items from a renowned boutique'),
    ('VWX234', 'Madrid', 'Toronto', 'In Transit', 3, 'Assorted collection of books for a book club'),
    ('BCD890', 'Amsterdam', 'Buenos Aires', 'Pending', 4, 'Toy collection for a kids\' store'),
    ('KLM789', 'Sydney', 'Berlin', 'In Transit', 5, 'Custom-designed furniture pieces'),
    ('TUV678', 'Cairo', 'Seoul', 'In Transit', 6, 'Jewelry items, securely packed'),
    ('BCD567', 'Buenos Aires', 'Amsterdam', 'In Transit', 7, 'Professional-grade tools for a construction project'),
    ('KLM456', 'Berlin', 'Sydney', 'In Transit', 8, 'Sports equipment for a local sports club'),
    ('TUV345', 'Seoul', 'Mumbai', 'In Transit', 9, 'Medical supplies for a health clinic'),
    ('BCD234', 'Amsterdam', 'Buenos Aires', 'In Transit', 10, 'Appliances for a new home'),
    ('DEF456', 'London', 'Paris', 'Delivered', 1, 'Latest electronics gadgets, high-demand products'),
    ('GHI789', 'Tokyo', 'Sydney', 'In Transit', 1, 'Cultural and artistic items for an exhibition'),
    ('MNO345', 'Moscow', 'Beijing', 'Delivered', 2, 'Furniture pieces for a luxury apartment'),
    ('PQR678', 'Dubai', 'Cairo', 'In Transit', 2, 'Delicate and valuable artworks'),
    ('STU901', 'Seoul', 'Mumbai', 'Pending', 3, 'Luxury clothing items, designer brands'),
    ('YZA567', 'Rio de Janeiro', 'Singapore', 'Delivered', 3, 'Antique furniture collection'),
    ('EFG123', 'Paris', 'New York', 'In Transit', 4, 'Medical equipment for a hospital'),
    ('HIJ456', 'Los Angeles', 'Tokyo', 'Delivered', 4, 'Electronics devices for a tech fair'),
    ('NOP012', 'Rome', 'Moscow', 'Pending', 5, 'High-end fashion items for a runway show'),
    ('QRS345', 'Beijing', 'Dubai', 'Delivered', 5, 'Rare and collectible books'),
    ('WXY901', 'Mumbai', 'Madrid', 'Pending', 6, 'Premium-quality toys for a specialty store'),
    ('ZAB234', 'Toronto', 'Rio de Janeiro', 'Delivered', 6, 'Art and craft supplies for a creative workshop'),
    ('EFG890', 'New York', 'Paris', 'Pending', 7, 'Musical instruments for a concert'),
    ('HIJ123', 'Tokyo', 'Los Angeles', 'Delivered', 7, 'Gourmet food items, perishable goods'),
    ('NOP789', 'Moscow', 'Rome', 'Pending', 8, 'Luxury clothing and accessories'),
    ('QRS012', 'Dubai', 'Beijing', 'Delivered', 8, 'Medical supplies for disaster relief'),
    ('WXY678', 'Madrid', 'Toronto', 'Pending', 9, 'Electronics products, latest gadgets'),
    ('ZAB901', 'Rio de Janeiro', 'Singapore', 'Delivered', 9, 'Specialty chocolates and sweets'),
    ('EFG567', 'Paris', 'New York', 'Pending', 10, 'Fashion items from emerging designers'),
    ('HIJ890', 'Los Angeles', 'Tokyo', 'Delivered', 10, 'High-tech gadgets for a tech expo');

    INSERT INTO parcels (weight, description, shipmentId) VALUES
        (12.5, 'Electronics', 1),
        (10, 'Electronics', 11),
        (9.5, 'Art', 12),
        (8.9, 'Clothing', 2),
        (6.0, 'Furniture', 13),
        (8.7, 'Art', 14),
        (9.5, 'Books', 3),
        (2.5, 'Clothing', 15),
        (1.5, 'Furniture', 16),
        (10.7, 'Toys', 4),
        (9.5, 'Medicine', 17),
        (12.3, 'Electronics', 18),
        (5.3, 'Furniture', 5),
        (15.5, 'Fashion', 19),
        (15.3, 'Books', 20),
        (9.5, 'Jewelry', 6),
        (6.7, 'Toys', 21),
        (8.9, 'Art', 22),
        (9.8, 'Tools', 7),
        (9.7, 'Music', 23),
        (9.8, 'Food', 24),
        (7.5, 'Sports Equipment', 8),
        (9.4, 'Clothing', 25),
        (7.2, 'Medicine', 26),
        (10.1, 'Appliances', 9),
        (11.9, 'Electronics', 27),
        (14.1, 'Sweets', 28),
        (11.1, 'Medical Supplies', 10),
        (13.6, 'Fashion', 29),
        (17.5, 'Tech', 30);

    INSERT INTO deliveryAgents (name, vehicleType, availability) VALUES
        ('Mike Johnson', 'Truck', true),
        ('Sarah Davis', 'Van', false),
        ('Emily Wilson', 'Bike', true),
        ('David Lee', 'Car', true),
        ('Sophie Brown', 'Truck', false),
        ('James Miller', 'Van', true),
        ('Lily Garcia', 'Bike', true),
        ('Matthew Martinez', 'Car', false),
        ('Grace White', 'Truck', true),
        ('Ethan Thomas', 'Van', true);

    INSERT INTO deliveryRoutes (routeName, agentId, shipmentId) VALUES
        ('Route 1', 1, 1),
        ('Route 2', 2, 2),
        ('Route 3', 3, 3),
        ('Route 4', 4, 4),
        ('Route 5', 5, 5),
        ('Route 6', 6, 6),
        ('Route 7', 7, 7),
        ('Route 8', 8, 8),
        ('Route 9', 9, 9),
        ('Route 10', 10, 10);
